export const ShopData = [
  {
    id: 1,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231993/cu2nnsrnszm4hqpvhwur.png",
    price: "25.00",
    title: "Galaxy 920",
    color: "blue",
  },
  {
    id: 2,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231990/fwlusgufpsyupaqplloh.png",
    price: "30.00",
    title: "iPhone 12",
    color: "black",
  },
  {
    id: 3,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/rzhjzikxsvnn5tgapbf9.png",
    price: "30.00",
    title: "iPhone 11",
    color: "white",
  },
  {
    id: 4,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/po4spgel27pto6rddkce.png",
    price: "30.00",
    title: "iPhone 6",
    color: "gold",
  },
  {
    id: 5,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231988/qxp5ioatrjgayrqnh0i4.png",
    price: "25.00",
    title: "Galaxy 920",
    color: "blue",
  },
  {
    id: 6,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231990/fwlusgufpsyupaqplloh.png",
    price: "30.00",
    title: "iPhone 12",
    color: "black",
  },
  {
    id: 7,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/rzhjzikxsvnn5tgapbf9.png",
    price: "30.00",
    title: "iPhone 11",
    color: "white",
  },
  {
    id: 8,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/po4spgel27pto6rddkce.png",
    price: "30.00",
    title: "iPhone 6",
    color: "gold",
  },
  {
    id: 9,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231988/qxp5ioatrjgayrqnh0i4.png",
    price: "25.00",
    title: "Galaxy 920",
    color: "blue",
  },
  {
    id: 10,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231990/fwlusgufpsyupaqplloh.png",
    price: "30.00",
    title: "iPhone 12",
    color: "black",
  },
  {
    id: 11,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/rzhjzikxsvnn5tgapbf9.png",
    price: "30.00",
    title: "iPhone 11",
    color: "white",
  },
  {
    id: 12,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/po4spgel27pto6rddkce.png",
    price: "30.00",
    title: "iPhone 6",
    color: "gold",
  },
  {
    id: 13,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231988/qxp5ioatrjgayrqnh0i4.png",
    price: "25.00",
    title: "Galaxy 920",
    color: "blue",
  },
  {
    id: 14,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231990/fwlusgufpsyupaqplloh.png",
    price: "30.00",
    title: "iPhone 12",
    color: "black",
  },
  {
    id: 15,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/rzhjzikxsvnn5tgapbf9.png",
    price: "30.00",
    title: "iPhone 11",
    color: "white",
  },
  {
    id: 16,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/po4spgel27pto6rddkce.png",
    price: "30.00",
    title: "iPhone 6",
    color: "gold",
  },
  {
    id: 17,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231988/qxp5ioatrjgayrqnh0i4.png",
    price: "25.00",
    title: "Galaxy 920",
    color: "blue",
  },
  {
    id: 18,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231990/fwlusgufpsyupaqplloh.png",
    price: "30.00",
    title: "iPhone 12",
    color: "black",
  },
  {
    id: 19,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/rzhjzikxsvnn5tgapbf9.png",
    price: "30.00",
    title: "iPhone 11",
    color: "white",
  },
  {
    id: 20,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/po4spgel27pto6rddkce.png",
    price: "30.00",
    title: "iPhone 6",
    color: "gold",
  },
  {
    id: 17,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231988/qxp5ioatrjgayrqnh0i4.png",
    price: "25.00",
    title: "Galaxy 920",
    color: "blue",
  },
  {
    id: 18,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231990/fwlusgufpsyupaqplloh.png",
    price: "30.00",
    title: "iPhone 12",
    color: "black",
  },
  {
    id: 19,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/rzhjzikxsvnn5tgapbf9.png",
    price: "30.00",
    title: "iPhone 11",
    color: "white",
  },
  {
    id: 20,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/po4spgel27pto6rddkce.png",
    price: "30.00",
    title: "iPhone 6",
    color: "gold",
  },
  {
    id: 17,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231988/qxp5ioatrjgayrqnh0i4.png",
    price: "25.00",
    title: "Galaxy 920",
    color: "blue",
  },
  {
    id: 18,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231990/fwlusgufpsyupaqplloh.png",
    price: "30.00",
    title: "iPhone 12",
    color: "black",
  },
  {
    id: 19,
    img: "https://res.cloudinary.com/dminu0vmy/image/upload/c_scale,w_300,q_auto/v1718231989/rzhjzikxsvnn5tgapbf9.png",
    price: "30.00",
    title: "iPhone 11",
    color: "white",
  },
];

//   normal Images

// export const ShopData = [
//   {
//     id: 1,
//     img: "https://res.cloudinary.com/dminu0vmy/image/upload/v1718231993/cu2nnsrnszm4hqpvhwur.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 2,
//     img: "https://res.cloudinary.com/dminu0vmy/image/upload/v1718231990/fwlusgufpsyupaqplloh.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 3,
//     img: "https://res.cloudinary.com/dminu0vmy/image/upload/v1718231989/rzhjzikxsvnn5tgapbf9.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
//   {
//     id: 4,
//     img: "https://res.cloudinary.com/dminu0vmy/image/upload/v1718231989/po4spgel27pto6rddkce.png",
//     price: "30.00",
//     title: "iPhone 6",
//     color: "gold",
//   },
//   {
//     id: 5,
//     img: "https://res.cloudinary.com/dminu0vmy/image/upload/v1718231988/qxp5ioatrjgayrqnh0i4.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 6,
//     img: "/images/two.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 7,
//     img: "/images/three.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
//   {
//     id: 8,
//     img: "/images/four.png",
//     price: "30.00",
//     title: "iPhone 6",
//     color: "gold",
//   },

//   {
//     id: 9,
//     img: "/images/one.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 10,
//     img: "/images/two.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 11,
//     img: "/images/three.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
//   {
//     id: 12,
//     img: "/images/four.png",
//     price: "30.00",
//     title: "iPhone 6",
//     color: "gold",
//   },
//   {
//     id: 13,
//     img: "/images/one.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 14,
//     img: "/images/two.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 15,
//     img: "/images/three.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
//   {
//     id: 16,
//     img: "/images/four.png",
//     price: "30.00",
//     title: "iPhone 6",
//     color: "gold",
//   },
//   {
//     id: 17,
//     img: "/images/one.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 18,
//     img: "/images/two.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 19,
//     img: "/images/three.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
//   {
//     id: 20,
//     img: "/images/four.png",
//     price: "30.00",
//     title: "iPhone 6",
//     color: "gold",
//   },
//   {
//     id: 17,
//     img: "/images/one.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 18,
//     img: "/images/two.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 19,
//     img: "/images/three.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
//   {
//     id: 20,
//     img: "/images/four.png",
//     price: "30.00",
//     title: "iPhone 6",
//     color: "gold",
//   },
//   {
//     id: 17,
//     img: "/images/one.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 18,
//     img: "/images/two.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 19,
//     img: "/images/three.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
//   {
//     id: 20,
//     img: "/images/four.png",
//     price: "30.00",
//     title: "iPhone 6",
//     color: "gold",
//   },
//   {
//     id: 17,
//     img: "/images/one.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 18,
//     img: "/images/two.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 19,
//     img: "/images/three.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
//   {
//     id: 20,
//     img: "/images/four.png",
//     price: "30.00",
//     title: "iPhone 6",
//     color: "gold",
//   },
//   {
//     id: 17,
//     img: "/images/one.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 18,
//     img: "/images/two.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 19,
//     img: "/images/three.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
//   {
//     id: 20,
//     img: "/images/four.png",
//     price: "30.00",
//     title: "iPhone 6",
//     color: "gold",
//   },
//   {
//     id: 17,
//     img: "/images/one.png",
//     price: "25.00",
//     title: "Galaxy 920",
//     color: "blue",
//   },
//   {
//     id: 18,
//     img: "/images/two.png",
//     price: "30.00",
//     title: "iPhone 12",
//     color: "black",
//   },

//   {
//     id: 19,
//     img: "/images/three.png",
//     price: "30.00",
//     title: "iPhone 11",
//     color: "white",
//   },
// ];
